name: GitEvents

on:
  push:
    branches:
      - main
  pull_request:
  issues:
    types: [opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 12
      - name: gitevents
        uses: gitevents/action@1.0.0
        with:
          enable-auto-invite: true
          gitevents-bot-login: 'cyprusjs-bot'
        env:
          GITHUB_TOKEN: ${{ secrets.GE_ADMIN_TOKEN }}
