name: New Talk Proposal
on:
  issues:
    types: [labeled]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        if: contains(github.event.issue.labels,'proposal')
        with:
          status: "New talk proposal: ${{github.event.issue.title}} ${{github.event.issue.html_url}} #CyprusJS"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}